#!/bin/bash

if uname -a | grep "NITRO-Endeavour" > /dev/null || uname -a | grep "NITRO-Arch" > /dev/null; then
  source ~/Dev/sh/universal-setup/endeavour.sh
elif uname -a | grep "Ubuntu" > /dev/null; then
  source ~/Dev/sh/universal-setup/ubuntu.sh
elif uname -a | grep "Android" > /dev/null; then
  source ~/Dev/sh/universal-setup/termux.sh
fi

source ~/Dev/sh/universal-setup/repos.sh

# tmux config
if [ ! -d ~/.tmux/plugins/tpm ]; then
  git clone git@github.com:tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
if [ ! -d ~/.config/tmux ]; then
  git clone git@github.com:thederpykrafter/tmux ~/.config/tmux
fi

# wakatime config
if ! grep "api_key = waka_" ~/.wakatime.cfg &> /dev/null; then
  ~/Dev/sh/universal-setup/wakatime.sh
fi
