#!/bin/bash

if ! git config --get user.name &> /dev/null; then
  git config --global user.name thederpykrafter
  git config --global user.email "thederpykrafter@gmail.com"
  git config --global init.defaultBranch main
  git config --global core.editor nvim
  git config --global color.ui auto
  echo -e "\e[94mSuccesfully configured Git\e[m"
fi

if ! gh auth status > /dev/null 2>&1; then
  gh auth login
fi

if [ -d ~/universal-setup ]; then
  if [ ! -d ~/Dev/sh ]; then
    mkdir -p ~/Dev/sh
  fi
  mv ~/universal-setup ~/Dev/sh/
elif [ ! -d ~/Dev/sh/universal-setup ]; then
  gh repo clone thederpykrafter/universal-setup.git ~/Dev/sh/universal-setup
fi

if uname -a | grep "NITRO-Endeavour" > /dev/null || uname -a | grep "NITRO-Arch" > /dev/null; then
  source ~/Dev/sh/universal-setup/endeavour.sh
elif uname -a | grep "Ubuntu" > /dev/null; then
  source ~/Dev/sh/universal-setup/ubuntu.sh
elif uname -a | grep "Android" > /dev/null; then
  source ~/Dev/sh/universal-setup/termux.sh
fi

# change shell to zsh
if echo $SHELL | grep "bash" > /dev/null; then
  chsh -s zsh
fi

# oh-my-zsh setup
if [ ! -d ~/.oh-my-zsh ]; then
  echo -e "\e[91m** EXIT ZSH TO CONTINUE INSTALL"
  echo -e "** PRESS <ENTER> TO CONTINUE **\e[m"
  read -e
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  echo -e "\e[94mSuccesfully installed oh-my-zsh\e[m"
fi

source ~/Dev/sh/universal-setup/repos.sh

# wakatime config
if ! grep "api_key = waka_" ~/.wakatime.cfg &> /dev/null; then
  ~/Dev/sh/universal-setup/wakatime.sh
fi

# rclone for google drive
if command -v rclone &> /dev/null; then
  if [ ! -f ~/.config/rclone/rclone.conf ]; then
    mkdir -p ~/.config/rclone/
    # @formatter:off
    echo '[Drive]
type = drive
scope = drive
token = {"access_token":"ya29.a0AXeO80QUsrIEvYaDAE47wayW2alVfEeffyR7zJAXRChqk1PZMn7FzoGGpnm30AgsYn4F9vm1vWI3PMQe9iDZF_akDQRy2CFbZ0nLsojU5-TodG8oikRBBDLedhtuqLIHU-Lfe-F1ErAKqMFtWfNrp_dRQrb1KbStRbop_cq-DQaCgYKAcwSARISFQHGX2Miq4CooU9j4hUDcdCoQWgQIg0177","token_type":"Bearer","refresh_token":"1//04Wl2aatQK1s_CgYIARAAGAQSNwF-L9IrTbW4CgcjlUj2qU1qD6xLp8Vd3ukQ4sj44dWZITNsGVMaeYh6n80wWSK-SHyw1fc0UFg","expiry":"2025-02-13T21:20:09.185368173-05:00"}
team_drive =
' > ~/.config/rclone/rclone.conf
    # @formatter:on
  fi

  rclone sync Drive:Retail\ Schedule\ .xlsx ~/Dev/sh/work-sched/sched/ --drive-shared-with-me

  cd ~/Dev/sh/work-sched
  if git status | grep "Retail" &> /dev/null; then
    git add .
    git commit -m "update schedule"
    echo -e "\e[91mSchedule updated!\e[m"
  fi
fi

if [ -d /run/media/thederpykrafter/KINGSTON ];
then
  if [ -d ~/Dev/sh/universal-setup ];
  then
    echo -e "\e[94mBacking up Universal Setup to Kingston\e[m"
    sudo cp -ru ~/Dev/sh/universal-setup /run/media/thederpykrafter/KINGSTON/
    echo -e "\e[94mBackup complete!\e[m"
  fi
elif [ -d ~/storage/shared/Documents ]; then
  if [ -d ~/Dev/sh/universal-setup ];
  then
    echo -e "\e[94mBacking up Universal Setup to Documents\e[m"
    cp -ru ~/Dev/sh/universal-setup ~/storage/shared/Documents
    echo -e "\e[94mBackup complete!\e[m"
  fi
fi
