#!/bin/bash

if uname -a | grep "NITRO-Endeavour" > /dev/null || uname -a | grep "NITRO-Arch" > /dev/null; then
  source ~/Dev/sh/universal-setup/endeavour.sh
elif uname -a | grep "Ubuntu" > /dev/null; then
  source ~/Dev/sh/universal-setup/ubuntu.sh
elif uname -a | grep "Android" > /dev/null; then
  source ~/Dev/sh/universal-setup/termux.sh
fi

source ~/Dev/sh/universal-setup/repos.sh


fi
