#!/bin/zsh

function shortcut() {
  cp -rf $1/$2 ~/.shortcuts/$(echo $2 | sed 's/\.sh//')
}

function task() {
  cp -rf $1/$2 ~/.shortcuts/$(echo task/$2 | sed 's/\.sh//')
}

shortcut ~/Dev/sh/get-repos get-repos.sh
shortcut ~/Dev/sh/universal-setup setup.sh
shortcut ~/Dev/sh/nogit nogit.sh

task ~/Dev/sh/work-sched work-sched

cd ~/.shortcuts
git pull
if git status | grep "modified" &> /dev/null; then
  git add .
  git commit -m "update shortcuts"
  git push
fi
