#!/bin/zsh

function shortcut() {
  cp $1/$2 ~/.shortcuts/$(echo $2 | sed 's/\.sh//')
}

shortcut ~/Dev/sh/get-repos get-repos.sh
shortcut ~/Dev/sh/universal-setup setup.sh
shortcut ~/Dev/sh/nogit nogit.sh
