#!/bin/bash

# get updated schedule
rclone sync Drive:Retail\ Schedule\ .xlsx ~/Dev/sh/work-sched/sched/ --drive-shared-with-me

# push schedule changes to git
cd ~/Dev/sh/work-sched
if git status | grep "Retail" &> /dev/null; then
  git add .
  git commit -m "update schedule"
  echo -e "\e[91mSchedule updated!\e[m"
fi

xdg-open sched/Retail\ Schedule\ .xlsx
